"""

Revision ID: 0912f47abd10
Revises: 
Create Date: 2025-12-28 19:55:39.323584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0912f47abd10'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('language', sa.String(), server_default='en', nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('downloaded_pdf', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('subscribed_to_channel', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('consultation_requested', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('consultation_declined', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('consultation_paid', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_message_date', sa.DateTime(), nullable=True),
    sa.Column('autoresponder_day', sa.BIGINT(), server_default='0', nullable=False),
    sa.Column('consultation_name', sa.String(), nullable=True),
    sa.Column('consultation_situation', sa.String(), nullable=True),
    sa.Column('consultation_concern', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
