"""add_pdf_downloaded_at_field

Revision ID: 2b006e12b514
Revises: 0912f47abd10
Create Date: 2026-01-03 16:18:13.820176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b006e12b514'
down_revision: Union[str, None] = '0912f47abd10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pdf_downloaded_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pdf_downloaded_at')
    # ### end Alembic commands ###
