"""add_payment_system

Revision ID: cf23380eef77
Revises: 2b006e12b514
Create Date: 2026-01-03 18:47:30.509000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf23380eef77'
down_revision: Union[str, None] = '2b006e12b514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create promo_codes table
    op.create_table('promo_codes',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('discount_percent', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )

    # Create pending_payments table
    op.create_table('pending_payments',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_type', sa.String(), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('promo_code', sa.String(), nullable=True),
    sa.Column('discount_percent', sa.Integer(), nullable=False),
    sa.Column('final_amount_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('screenshot_file_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # Add new fields to users table
    op.add_column('users', sa.Column('has_paid_pdf', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('has_community_access', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('community_paid_until', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('has_paid_consultation_300', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove columns from users table
    op.drop_column('users', 'has_paid_consultation_300')
    op.drop_column('users', 'community_paid_until')
    op.drop_column('users', 'has_community_access')
    op.drop_column('users', 'has_paid_pdf')

    # Drop tables
    op.drop_table('pending_payments')
    op.drop_table('promo_codes')
    # ### end Alembic commands ###
